name: Compile LaTeX on EC2

on:
  push:
    paths:
      - "**.tex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload LaTeX file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "main.tex"
          target: "latex_build/"
          strip_components: 0
          debug: true

      - name: Compile LaTeX on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export PATH=/usr/local/texlive/2024/bin/x86_64-linux:$PATH
            cd ~/latex_build
            pdflatex -interaction=nonstopmode main.tex
            ls -lh

      - name: Copy compiled PDF to /tmp
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cp ~/latex_build/main.pdf /tmp/main.pdf

      - name: Download PDF from EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "/tmp/main.pdf"
          target: "./"
          debug: true

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf
          
