name: Build LaTeX on EC2 and Get PDF

on:
  push:
    paths:
      - '**.tex'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LaTeX source
        uses: actions/checkout@v3

      - name: Copy .tex to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "*.tex"
          target: "/home/ec2-user/latex_build"

      - name: Compile LaTeX on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export PATH=/usr/local/texlive/2024/bin/x86_64-linux:$PATH
            cd ~/latex_build
            pdflatex main.tex

      - name: Copy PDF back from EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "/home/ec2-user/latex_build/main.pdf"
          target: "./"

      - name: Upload PDF to GitHub as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf

