name: Download PDF from EC2

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'PDF file to download (e.g., main.pdf)'
        required: true
        default: 'main.pdf'

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download PDF via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "/home/ec2-user/latex_build/${{ github.event.inputs.filename }}"
          target: "./"
          strip_components: 0
          debug: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-pdf
          path: ${{ github.event.inputs.filename }}
